# config file for CLIP

training:
  debug: False
  batch_size: 5
  num_workers: 4
  head_lr: 1e-3
  image_encoder_lr: 1e-4
  text_encoder_lr: 1e-5
  weight_decay: 1e-3
  patience: 1
  factor: 0.8
  epochs: 4
  device: "cuda"
  pretrained: True
  trainable: True
  temperature: 1.0


paths:
  image_path: "./Datasets/Images"
  captions_path: "./Datasets"

model:
  model_name: 'resnet50'  # image encoder
  image_embedding: 2048
  text_encoder_model: "./distilbert-base-uncased/"
  text_embedding: 768
  text_tokenizer: "./distilbert-base-uncased/"
  max_length: 200
  num_projection_layers: 1
  projection_dim: 256
  dropout: 0.1
  size: 224

